[tasks.dbreset]
# マイグレーションファイルが3つあるので3回revertしてからrunする
description = "Reset data the database"
script = """
sqlx mig revert
sqlx mig revert
sqlx mig revert
sqlx mig run
"""


[tasks.apitest]
description = "Run API tests"
script = """
httpyac -a ./tests/user_create_get_login_update.http
"""
dependencies = ["dbreset"]