[tasks.dbreset]
# マイグレーションファイルが3つあるので3回revertしてからrunする
description = "Reset data the database"
script = """
# migrationsフォルダ内にある，down.sqlの数だけrevertしてからrunする
# forで制御する
# migrartoinsフォルダ内にある，down.sqlの数を取得
down_sql_count=$(ls migrations/*.down.sql | wc -l)
for i in $(seq 1 $down_sql_count); do
    sqlx mig revert
    echo "revert $i"
done

sqlx mig run
"""


[tasks.apitest]
description = "Run API tests"
script = """
echo "user create get update login: ユーザー"
httpyac -a ./tests/user_create_get_update_login.http
echo "user create get update with password login: ユーザー パスワードも更新"
httpyac -a ./tests/user_create_get_update-with-password_login.http
echo "Follow: フォロー"
httpyac -a ./tests/follow_getProfile_unfollow.http
echo "Article: 記事"
httpyac -a ./tests/articles.http
echo "Favorite: いいね"
httpyac -a ./tests/favorites.http
"""
dependencies = ["dbreset"]