name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://conduit:postgres@localhost:5432/conduit
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.80.1
    - uses: Swatinem/rust-cache@v2
    - run: sudo systemctl start postgresql.service
    - run: pg_isready
    - run: sudo -u postgres psql --command="CREATE USER conduit WITH SUPERUSER PASSWORD 'postgres'" --command="\du" postgres
    - run: sudo -u postgres createdb --owner=conduit conduit
    - uses: baptiste0928/cargo-install@v3.1.1
      name: Install sqlx-cli
      with:
        crate: sqlx-cli
    - name: migrate
      run: sqlx mig run
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  # typos単体で結果を見たいのでJobを分ける
  typos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: typos-action
      uses: crate-ci/typos@v1.24.6

